"""Generate include/version.h with the firmware version before every build.

Uses `git describe` so a build from a tagged release (e.g. v1.0.1, the tags
the build-and-release.yaml workflow publishes to GitHub Releases) embeds that
exact tag, while a local/dev build gets a commit-based fallback instead of a
hardcoded string that would go stale.
"""

import os
import subprocess

Import("env")  # noqa: F821  (PlatformIO injects this at exec time)


def get_version() -> str:
    try:
        return (
            subprocess.check_output(
                ["git", "describe", "--tags", "--always", "--dirty"],
                stderr=subprocess.DEVNULL,
            )
            .strip()
            .decode("utf-8")
        )
    except Exception:
        return "unknown"


def write_version_header():
    version = get_version()
    include_dir = os.path.join(env.subst("$PROJECT_DIR"), "include")
    os.makedirs(include_dir, exist_ok=True)
    header_path = os.path.join(include_dir, "version.h")

    content = (
        "// Auto-generated by scripts/generate_version.py - do not edit.\n"
        "#pragma once\n"
        f'#define FIRMWARE_VERSION "{version}"\n'
    )

    # Avoid useless rebuilds if the version did not actually change.
    if os.path.exists(header_path):
        with open(header_path) as f:
            if f.read() == content:
                return

    with open(header_path, "w") as f:
        f.write(content)

    print(f"[generate_version] FIRMWARE_VERSION = {version}")


write_version_header()
